sudo: false
language: node_js
addons:
  apt:
    packages:
      - xvfb
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '7'
before_install:
  - npm i -g npm@latest
install:
  - "export DISPLAY=':99.0'"
  - 'Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &'
  - npm install
before_script:
  - npm run lint
script:
  - npm test
after_success:
  - npm run autorelease
branches:
  only:
    - "master"
